# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22fcd57d03cca8f26b06c3ab1798fc575867b2263b3ceaa9db2a00964d99ec694206d1d10a6ebf7621dcc419997ee578949fe2e35adce82dedabc001e9f55e7e

test:
  secret_key_base: ab8f52b1eeed5ec613dc8476bebd69536f4ca18b85aa3d0eb39ba26ff8a0aaaa82c65275563c700831b9cfcdbfc544b6d1b1d3cfc5de596892ebdd770c02fd97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
